# Generated by Django on 2025-11-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='last_login_date',
            field=models.DateField(blank=True, null=True, verbose_name='Último login'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='streak_count',
            field=models.IntegerField(default=0, verbose_name='Dias consecutivos'),
        ),
    ]