# Generated by Django 5.2 on 2025-11-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_auto_20251110_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='last_name_change',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='last_edit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última edição do perfil'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Foto de Perfil'),
        ),
    ]
