# Generated by Django 5.2.4 on 2025-11-30 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('icone', models.CharField(blank=True, help_text='Ex: 📐, 📚, 🧪', max_length=10, verbose_name='Ícone (emoji)')),
            ],
            options={
                'verbose_name': 'Matéria',
                'verbose_name_plural': 'Matérias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LinkExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_site', models.CharField(help_text='Ex: Toda Matéria, Brasil Escola, Khan Academy', max_length=100, verbose_name='Nome do Site')),
                ('url', models.URLField(help_text='Ex: https://www.todamateria.com.br/historia/', verbose_name='URL Completo')),
                ('descricao', models.CharField(blank=True, help_text='Breve descrição do conteúdo do site', max_length=200, verbose_name='Descrição')),
                ('ordem', models.IntegerField(default=0, help_text='Número para ordenar (1, 2, 3...)', verbose_name='Ordem de Exibição')),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para desativar temporariamente', verbose_name='Ativo')),
                ('adicionado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links_adicionados', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_externos', to='materias.subject')),
            ],
            options={
                'verbose_name': 'Link Externo',
                'verbose_name_plural': 'Links Externos',
                'ordering': ['materia', 'ordem', 'nome_site'],
            },
        ),
    ]
