# Generated by Django 5.2.4 on 2025-11-25 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('map', 'Mapa Mental'), ('res', 'Resumo'), ('vid', 'Vídeoaula'), ('exe', 'Lista de Exercícios'), ('doc', 'PDF/Doc'), ('other', 'Outro')], max_length=10)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('external_url', models.URLField(blank=True, help_text='Link do vídeo/external resource (opcional)')),
                ('file', models.FileField(blank=True, null=True, upload_to='materias/files/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='materias/thumbs/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='materias.subject')),
            ],
            options={
                'ordering': ['-recommended', '-created_at'],
            },
        ),
    ]
