# Generated by Django 5.2.4 on 2025-11-30 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkexterno',
            name='adicionado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='linkexterno',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='linkexterno',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='linkexterno',
            name='nome_site',
            field=models.CharField(max_length=100, verbose_name='Nome do Site'),
        ),
        migrations.AlterField(
            model_name='linkexterno',
            name='ordem',
            field=models.IntegerField(default=0, verbose_name='Ordem de Exibição'),
        ),
        migrations.AlterField(
            model_name='linkexterno',
            name='url',
            field=models.URLField(verbose_name='URL Completo'),
        ),
    ]
