# Generated by Django 5.2.6 on 2025-11-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_login',
            field=models.BooleanField(default=True, verbose_name='Primeiro Login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrador'), ('professor', 'Professor'), ('aluno', 'Aluno')], default='aluno', max_length=20, verbose_name='Tipo de Usuário'),
        ),
    ]
