# Generated by Django 5.2.6 on 2025-11-01 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, max_length=400, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='note',
            name='file_type',
            field=models.CharField(choices=[('DOC', 'Documento Word'), ('PDF', 'PDF'), ('PPT', 'Apresentação'), ('LINK', 'Link Externo')], max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
        migrations.CreateModel(
            name='NoteRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_at', models.DateTimeField(auto_now_add=True, verbose_name='Recomendado em')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='notes.note', verbose_name='Note')),
                ('teacher', models.ForeignKey(limit_choices_to={'user_type': 'professor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Recomendação',
                'verbose_name_plural': 'Recomendações',
                'ordering': ['-recommended_at'],
                'unique_together': {('note', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='NoteView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Visualizado em')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_views', to='notes.note', verbose_name='Note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Visualização',
                'verbose_name_plural': 'Visualizações',
                'indexes': [models.Index(fields=['note', 'user'], name='notes_notev_note_id_f3c015_idx'), models.Index(fields=['-viewed_at'], name='notes_notev_viewed__877240_idx')],
                'unique_together': {('note', 'user')},
            },
        ),
    ]
