# Generated by Django 5.2.6 on 2025-12-02 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_description_alter_note_file_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Matéria')),
            ],
            options={
                'verbose_name': 'Matéria (Notes)',
                'verbose_name_plural': 'Matérias (Notes)',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveIndex(
            model_name='note',
            name='notes_note_subject_435eb9_idx',
        ),
        migrations.RemoveField(
            model_name='note',
            name='subject',
        ),
        migrations.AddField(
            model_name='note',
            name='subject_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='notes.materia', verbose_name='Matéria'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['subject_new'], name='notes_note_subject_d71443_idx'),
        ),
    ]
