# Generated by Django 5.2.6 on 2025-11-23 02:10

import atividades.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, max_length=800, verbose_name='Descrição/Orientações')),
                ('tipo', models.CharField(choices=[('ATIVIDADE', 'Atividade'), ('AVISO_PROVA', 'Aviso de Prova'), ('AVISO_SIMPLES', 'Aviso Simples')], max_length=20, verbose_name='Tipo de Atividade')),
                ('ano_1', models.BooleanField(default=False, verbose_name='1º Ano')),
                ('ano_2', models.BooleanField(default=False, verbose_name='2º Ano')),
                ('ano_3', models.BooleanField(default=False, verbose_name='3º Ano')),
                ('todos', models.BooleanField(default=False, verbose_name='Todos os Anos')),
                ('prazo_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Prazo de Entrega')),
                ('permite_envio', models.BooleanField(default=True, verbose_name='Permite Envio pelo Aluno')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='atividades_anexos/', validators=[atividades.models.validate_file_size_atividade, atividades.models.validate_file_extension_atividade], verbose_name='Anexo')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('visualizacoes', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('foi_visualizado', models.BooleanField(default=False, verbose_name='Foi Visualizado por Algum Aluno')),
                ('professor', models.ForeignKey(limit_choices_to={'user_type': 'professor'}, on_delete=django.db.models.deletion.CASCADE, related_name='atividades_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AtividadeEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='atividades_envios/', validators=[atividades.models.validate_file_size_atividade, atividades.models.validate_file_extension_atividade], verbose_name='Arquivo')),
                ('status', models.CharField(choices=[('ENVIADA', 'Enviada'), ('CORRIGIDA', 'Corrigida')], default='ENVIADA', max_length=20, verbose_name='Status')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback do Professor')),
                ('aluno', models.ForeignKey(limit_choices_to={'user_type': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='atividades.atividade', verbose_name='Atividade')),
            ],
            options={
                'verbose_name': 'Envio de Atividade',
                'verbose_name_plural': 'Envios de Atividades',
                'ordering': ['-enviado_em'],
                'unique_together': {('atividade', 'aluno')},
            },
        ),
        migrations.CreateModel(
            name='AtividadeSalva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salva_em', models.DateTimeField(auto_now_add=True, verbose_name='Salva em')),
                ('aluno', models.ForeignKey(limit_choices_to={'user_type': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atividades.atividade', verbose_name='Atividade')),
            ],
            options={
                'verbose_name': 'Atividade Salva',
                'verbose_name_plural': 'Atividades Salvas',
                'ordering': ['-salva_em'],
                'unique_together': {('aluno', 'atividade')},
            },
        ),
        migrations.CreateModel(
            name='AtividadeVisualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualizado_em', models.DateTimeField(auto_now_add=True, verbose_name='Visualizado em')),
                ('aluno', models.ForeignKey(limit_choices_to={'user_type': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes_atividade', to='atividades.atividade', verbose_name='Atividade')),
            ],
            options={
                'verbose_name': 'Visualização de Atividade',
                'verbose_name_plural': 'Visualizações de Atividades',
                'ordering': ['-visualizado_em'],
                'unique_together': {('atividade', 'aluno')},
            },
        ),
    ]
