# Generated by Django 5.2.6 on 2025-11-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição/Orientações'),
        ),
    ]
