# Generated by Django 5.2.6 on 2025-11-24 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_alter_atividade_descricao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Professor'),
        ),
        migrations.AlterField(
            model_name='atividadeenvio',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='atividadesalva',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='atividadevisualizacao',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Aluno'),
        ),
    ]
