# Generated by Django 5.2.6 on 2025-11-30 18:47

import django.db.models.deletion
import horarios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='horarios/', validators=[horarios.models.validate_file_size_horario, horarios.models.validate_file_extension_horario], verbose_name='Arquivo')),
                ('tipo', models.CharField(choices=[('IMAGEM', 'Imagem'), ('EXCEL', 'Planilha Excel')], max_length=10, verbose_name='Tipo')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de importação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('importado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_importados', to=settings.AUTH_USER_MODEL, verbose_name='Importado por')),
            ],
            options={
                'verbose_name': 'Horário',
                'verbose_name_plural': 'Horários',
                'ordering': ['-data_importacao'],
            },
        ),
    ]
